import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { FinalModelResult } from "./types.js";

export interface GeneratedCardPaths {
  txtPath: string;
  htmlPath: string;
}

export function normalizeOutputBasePath(basePath: string): string {
  return basePath.replace(/\.(txt|html)$/i, "");
}

export async function generateCards(
  prompt: string,
  results: FinalModelResult[],
  basePath: string,
): Promise<GeneratedCardPaths> {
  const normalizedBasePath = normalizeOutputBasePath(basePath);
  const txtContent = generateAsciiCard(prompt, results);
  const htmlContent = generateHtmlCard(prompt, results);
  const txtPath = `${normalizedBasePath}.txt`;
  const htmlPath = `${normalizedBasePath}.html`;

  await mkdir(dirname(normalizedBasePath), { recursive: true });

  await Promise.all([
    writeFile(txtPath, txtContent, "utf-8"),
    writeFile(htmlPath, htmlContent, "utf-8"),
  ]);

  return { txtPath, htmlPath };
}

function generateAsciiCard(
  prompt: string,
  results: FinalModelResult[],
): string {
  const width = 78;
  const hr = "═".repeat(width);
  const thinHr = "─".repeat(width);
  const winner = results[0];

  const lines: string[] = [];
  lines.push(`╔${hr}╗`);
  lines.push(`║${center("LLM BENCH — Results", width)}║`);
  lines.push(`╠${hr}╣`);

  if (winner) {
    lines.push(
      `║${center(`🏆 Winner: ${winner.name} (score: ${winner.overallScore.toFixed(1)})`, width)}║`,
    );
    lines.push(`╠${hr}╣`);
  }

  lines.push(`║${padRight(`  Prompt: ${truncate(prompt, width - 12)}`, width)}║`);
  lines.push(`╠${hr}╣`);

  const header = formatRow(
    "Rank",
    "Model",
    "Time",
    "Cost",
    "Quality",
    "Overall",
  );
  lines.push(`║${padRight(header, width)}║`);
  lines.push(`║${thinHr}║`);

  results.forEach((result, index) => {
    const row = formatRow(
      `  ${index + 1}.`,
      result.name,
      formatTime(result.elapsedMs),
      formatCost(result.costUsd),
      result.qualityScore.toFixed(1),
      result.overallScore.toFixed(1),
    );
    lines.push(`║${padRight(row, width)}║`);
  });

  lines.push(`╠${hr}╣`);
  lines.push(
    `║${center("Generated by llm-bench — github.com/BuildWithAbid/llm-bench", width)}║`,
  );
  lines.push(`╚${hr}╝`);

  return `${lines.join("\n")}\n`;
}

function generateHtmlCard(
  prompt: string,
  results: FinalModelResult[],
): string {
  const winner = results[0];
  const timestamp = new Date().toISOString().split("T")[0];

  const rows = results
    .map(
      (result, index) => `
        <tr class="${index === 0 ? "winner" : ""}">
          <td class="rank">${index === 1 ? "🥈" : index === 2 ? "🥉" : index === 0 ? "🥇" : `${index + 1}.`}</td>
          <td class="model">${escapeHtml(result.name)}</td>
          <td>${formatTime(result.elapsedMs)}</td>
          <td>${formatCost(result.costUsd)}</td>
          <td>${result.inputTokens + result.outputTokens}</td>
          <td>
            <div class="score-bar">
              <div class="score-fill" style="width: ${result.speedScore * 10}%"></div>
            </div>
            ${result.speedScore.toFixed(1)}
          </td>
          <td>
            <div class="score-bar">
              <div class="score-fill cost" style="width: ${result.costScore * 10}%"></div>
            </div>
            ${result.costScore.toFixed(1)}
          </td>
          <td>
            <div class="score-bar">
              <div class="score-fill quality" style="width: ${result.qualityScore * 10}%"></div>
            </div>
            ${result.qualityScore.toFixed(1)}
          </td>
          <td class="overall">${result.overallScore.toFixed(1)}</td>
        </tr>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LLM Bench Results</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace;
    background: #0d1117;
    color: #c9d1d9;
    display: flex;
    justify-content: center;
    padding: 40px 20px;
  }
  .card {
    width: 680px;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 12px;
    overflow: hidden;
  }
  .header {
    background: linear-gradient(135deg, #1a1e2e 0%, #2d1b4e 50%, #1b2838 100%);
    padding: 28px 32px;
    border-bottom: 1px solid #30363d;
  }
  .header h1 {
    font-size: 22px;
    font-weight: 700;
    color: #f0f6fc;
    margin-bottom: 8px;
  }
  .header h1 span { color: #58a6ff; }
  .prompt {
    font-size: 13px;
    color: #8b949e;
    margin-top: 12px;
    padding: 8px 12px;
    background: rgba(0, 0, 0, 0.3);
    border-radius: 6px;
    font-family: monospace;
  }
  .winner-banner {
    background: linear-gradient(90deg, rgba(63, 185, 80, 0.15) 0%, transparent 100%);
    border-left: 3px solid #3fb950;
    padding: 14px 32px;
    font-size: 15px;
  }
  .winner-banner strong { color: #3fb950; }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }
  th {
    text-align: left;
    padding: 10px 12px;
    color: #8b949e;
    font-weight: 600;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    border-bottom: 1px solid #21262d;
  }
  td {
    padding: 10px 12px;
    border-bottom: 1px solid #21262d;
    vertical-align: middle;
  }
  tr.winner td { background: rgba(63, 185, 80, 0.06); }
  .rank { font-size: 16px; width: 36px; text-align: center; }
  .model { font-weight: 600; color: #f0f6fc; }
  .overall { font-weight: 700; color: #58a6ff; font-size: 15px; }
  tr.winner .overall { color: #3fb950; }
  .score-bar {
    width: 50px;
    height: 6px;
    background: #21262d;
    border-radius: 3px;
    overflow: hidden;
    display: inline-block;
    vertical-align: middle;
    margin-right: 6px;
  }
  .score-fill {
    height: 100%;
    background: #58a6ff;
    border-radius: 3px;
  }
  .score-fill.cost { background: #d2a8ff; }
  .score-fill.quality { background: #3fb950; }
  .footer {
    padding: 16px 32px;
    text-align: center;
    color: #484f58;
    font-size: 12px;
    border-top: 1px solid #21262d;
  }
  .footer a { color: #58a6ff; text-decoration: none; }
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <h1><span>⚡</span> LLM Bench Results</h1>
    <div style="color: #8b949e; font-size: 13px;">${escapeHtml(timestamp)}</div>
    <div class="prompt">"${escapeHtml(truncate(prompt, 120))}"</div>
  </div>
  ${winner ? `<div class="winner-banner">🏆 <strong>${escapeHtml(winner.name)}</strong> wins with a score of <strong>${winner.overallScore.toFixed(1)}</strong> — ${formatTime(winner.elapsedMs)}, ${formatCost(winner.costUsd)}</div>` : ""}
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Model</th>
        <th>Time</th>
        <th>Cost</th>
        <th>Tokens</th>
        <th>Speed</th>
        <th>Cost</th>
        <th>Quality</th>
        <th>Overall</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <div class="footer">
    Generated by <a href="https://github.com/BuildWithAbid/llm-bench">llm-bench</a>
  </div>
</div>
</body>
</html>`;
}

function formatTime(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function formatCost(cost: number): string {
  if (cost === 0) return "—";
  if (cost < 0.001) return `$${cost.toFixed(6)}`;
  return `$${cost.toFixed(4)}`;
}

function truncate(value: string, max: number): string {
  return value.length > max ? `${value.slice(0, max - 3)}...` : value;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function center(text: string, width: number): string {
  const pad = Math.max(0, width - text.length);
  const left = Math.floor(pad / 2);
  const right = pad - left;
  return `${" ".repeat(left)}${text}${" ".repeat(right)}`;
}

function padRight(text: string, width: number): string {
  const pad = Math.max(0, width - text.length);
  return `${text}${" ".repeat(pad)}`;
}

function formatRow(
  rank: string,
  model: string,
  time: string,
  cost: string,
  quality: string,
  overall: string,
): string {
  return `  ${rank.padEnd(6)}${model.padEnd(22)}${time.padEnd(10)}${cost.padEnd(12)}${quality.padEnd(10)}${overall}`;
}
